### ISSUE TITLE
Hash missmatch when downloading icu

### ISSUE THREAD

**Issue by pjako** [mapbox/mapbox-icu-js#2]
Running build.sh the script tries to fetch the icu source files. Looks like the hashes are missmatching.

http://download.icu-project.org/files/icu4c/58.1/icu4c-58_1-src.tgz
icu58_1.tgz
```
Hash fe9dcbd4f7b3d1caa4d8878e25e13a1e4e014f8a of icu58_1.tgz doesn't match ad6995ba349ed79dde0f25d125a9b0bb56979420
```

When I replace the hash with an '*' it runs through but it errors later on. It looks like there are files missing in the icu source code

```
cp: icu: No such file or directory
Build ICU tools with --host=x86_64-apple-darwin in /Users/p.jakobs/projects/mapbox-gl-rtl-text/icu/source/.build
./build.sh: line 49: pushd: /Users/p.jakobs/projects/mapbox-gl-rtl-text/icu/source: No such file or directory
./build.sh: line 59: ./configure: No such file or directory
cat: config.log: No such file or directory
rm -rf build
rm -f index.js
mkdir -p build
mkdir -p build
node_modules/buble/bin/buble src/icu.js -y dangerousForOf > build/icu.js
/emcc -Oz -c src/ubidi_wrapper.c -I./icu-llvm/source/common -o build/ubidi_wrapper.o
make: /emcc: No such file or directory
/emcc -Oz -c src/ushape_wrapper.c -I./icu-llvm/source/common -o build/ushape_wrapper.o
make: /emcc: No such file or directory
make: *** [build/ubidi_wrapper.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [build/ushape_wrapper.o] Error 1
/bin/sh: node_modules/buble/bin/buble: No such file or directory
make: *** [build/icu.js] Error 127
make: *** No rule to make target `install'.  Stop.
./build.sh: line 84: popd: directory stack empty
Downloading: /Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/zips/emsdk_unix_update.tar.gz from https://s3.amazonaws.com/mozilla-games/emscripten/packages/emsdk_unix_update.tar.gz
Unpacking '/Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/zips/emsdk_unix_update.tar.gz' to '/Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable'
x emscripten-tags.txt
x emsdk
x emsdk_env.sh
x emsdk_manifest.json
x README.md
Fetching all tags from Emscripten Github repository...
Done. 90 tagged releases available, latest is 1.37.3.
Installing SDK 'sdk-1.35.0-64bit'..
Installing tool 'clang-e1.35.0-64bit'..
The contents of file 'emscripten-clang_e1.35.0.tar.gz' already exist in destination '/Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/clang/e1.35.0_64bit', skipping.
Done installing tool 'clang-e1.35.0-64bit'.
Installing tool 'node-4.1.1-64bit'..
The contents of file 'node-v4.1.1-darwin-x64.tar.gz' already exist in destination '/Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/node/4.1.1_64bit', skipping.
Done installing tool 'node-4.1.1-64bit'.
Installing tool 'emscripten-1.35.0'..
The contents of file 'emscripten-1.35.0.tar.gz' already exist in destination '/Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/emscripten/1.35.0', skipping.
Done installing tool 'emscripten-1.35.0'.
Done installing SDK 'sdk-1.35.0-64bit'.
Writing .emscripten configuration file to user home directory /Users/p.jakobs/
The Emscripten configuration file /Users/p.jakobs/.emscripten has been rewritten with the following contents:

import os
LLVM_ROOT='/Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/clang/e1.35.0_64bit'
EMSCRIPTEN_NATIVE_OPTIMIZER='/Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/clang/e1.35.0_64bit/optimizer'
NODE_JS='/Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/node/4.1.1_64bit/bin/node'
EMSCRIPTEN_ROOT='/Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/emscripten/1.35.0'
SPIDERMONKEY_ENGINE = ''
V8_ENGINE = ''
TEMP_DIR = '/var/folders/ng/yd41pq0962n1wt4yc8r2_v040000gp/T'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

To conveniently access the selected set of tools from the command line, consider adding the following directories to PATH, or call 'source emsdk_portable/emsdk_env.sh' to do this for you.

   /Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable:/Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/clang/e1.35.0_64bit:/Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/node/4.1.1_64bit/bin:/Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/emscripten/1.35.0
Adding directories to PATH:
PATH += /Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable
PATH += /Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/clang/e1.35.0_64bit
PATH += /Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/node/4.1.1_64bit/bin
PATH += /Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/emscripten/1.35.0

Setting environment variables:
EM_CONFIG = /Users/p.jakobs/.emscripten
EMSCRIPTEN = /Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/emscripten/1.35.0

Building LLVM ICU with --host=x86_64-apple-darwin in /Users/p.jakobs/projects/mapbox-gl-rtl-text/icu-llvm/source/.build
./build.sh: line 90: pushd: /Users/p.jakobs/projects/mapbox-gl-rtl-text/icu-llvm/source: No such file or directory
sed: /Users/p.jakobs/projects/mapbox-gl-rtl-text/icu-llvm/source/config/mh-darwin: No such file or directory
sed: /Users/p.jakobs/projects/mapbox-gl-rtl-text/icu-llvm/source/configure: No such file or directory
sed: /Users/p.jakobs/projects/mapbox-gl-rtl-text/icu-llvm/source/configure: No such file or directory
ERROR:root:Exception thrown when invoking Popen in configure with args: "./configure --host=x86_64-apple-darwin --prefix=/Users/p.jakobs/projects/mapbox-gl-rtl-text/icu-llvm/source/.build --with-cross-build=/Users/p.jakobs/projects/mapbox-gl-rtl-text/icu/source --with-data-packaging=archive --enable-renaming --enable-strict --enable-static --enable-draft --enable-release --disable-tools --disable-debug --disable-rpath --disable-shared --disable-tests --disable-extras --disable-tracing --disable-layout --disable-icuio --disable-samples --disable-dyload"!
Traceback (most recent call last):
  File "/Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/emscripten/1.35.0/emconfigure", line 41, in <module>
    shared.Building.configure(sys.argv[1:])
  File "/Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/emscripten/1.35.0/tools/shared.py", line 1140, in configure
    process = Popen(args, stdout=None if EM_BUILD_VERBOSE_LEVEL >= 2 else stdout, stderr=None if EM_BUILD_VERBOSE_LEVEL >= 1 else stderr, env=env)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
cat: config.log: No such file or directory
rm -rf build
rm -f index.js
mkdir -p build
mkdir -p build
node_modules/buble/bin/buble src/icu.js -y dangerousForOf > build/icu.js
/Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/emscripten/1.35.0/emcc -Oz -c src/ubidi_wrapper.c -I./icu-llvm/source/common -o build/ubidi_wrapper.o
/Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/emscripten/1.35.0/emcc -Oz -c src/ushape_wrapper.c -I./icu-llvm/source/common -o build/ushape_wrapper.o
/bin/sh: node_modules/buble/bin/buble: No such file or directory
make: *** [build/icu.js] Error 127
make: *** Waiting for unfinished jobs....
INFO:root:(Emscripten: Running sanity checks)
INFO:root:(Emscripten: Running sanity checks)
src/ushape_wrapper.c:4:10: fatal error: 'unicode/ushape.h' file not found
#include <unicode/ushape.h>
         ^
1 error generated.
src/ubidi_wrapper.c:4:10: fatal error: 'unicode/ubidi.h' file not found
#include <unicode/ubidi.h>
         ^
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
make: *** [build/ushape_wrapper.o] Error 1
make: *** [build/ubidi_wrapper.o] Error 1
make: *** No rule to make target `install'.  Stop.
./build.sh: line 133: popd: directory stack empty
rm -rf build
rm -f index.js
mkdir -p build
/Users/p.jakobs/projects/mapbox-gl-rtl-text/emsdk_portable/emscripten/1.35.0/emcc -Oz -c src/ushape_wrapper.c -I./icu-llvm/source/common -o build/ushape_wrapper.o
WARNING:root:(Emscripten: settings file has changed, clearing cache)
INFO:root:(Emscripten: Running sanity checks)
src/ushape_wrapper.c:4:10: fatal error: 'unicode/ushape.h' file not found
#include <unicode/ushape.h>
         ^
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
make: *** [build/ushape_wrapper.o] Error 1
```

**Comment by ChrisLoer** [comment]
@pjako Sorry for the long delay, I missed the notification for this issue. 😓 

The problem was that curl wasn't following a redirect, it should be fixed by this commit: https://github.com/mapbox/mapbox-gl-rtl-text/commit/6ea28d68ab2de880f5648af6664ff216e49ccc48#diff-0b83f9dedf40d7356e5ca147a077acb4
